package passwordgenerator.util;
import java.io.File;
import java.io.FileWriter; //to output
import java.io.IOException;
import java.util.LinkedList;

public class SimpleFileWriter {
	private FileWriter writing;
	private File out;
	private LinkedList<String> nameData, emailData;
	/**
	 * A constructor for <code>SimpleFileWriter</code> that takes in a 
	 * <code>File</code> and two sets of <code>LinkedList<String></code>
	 * 
	 * @param file				The file to output to
	 * @param readDataNames		The data determined to be names
	 * @param readDataEmail		The data determined to be emails
	 */
	public SimpleFileWriter(File file, LinkedList<String> readDataNames,
			                LinkedList<String> readDataEmail)
	{
		try
		{
			out = file.getAbsoluteFile();
			nameData = readDataNames;
			emailData = readDataEmail;
			writing = new FileWriter(out, true);
		}
		catch(IOException e)
		{
			e.printStackTrace();
		}
	}
        
        public SimpleFileWriter(File file)
        {
            try
            {
                out = file.getAbsoluteFile();
                writing = new FileWriter(out, true);
            }
            catch(Exception e)
            {}
        }
	
	public void savePassword(String name, String password)
	{
                System.out.println(name + "   " + password);
                try{
		writing.write(name + " " + password + "\n");
                writing.close();}catch(Exception e){}
                
	}

	
	/**
	 * writeHTML is a class that writes the basic structure of a HTML file
	 * to the HTML file that is to be generated by the class. It returns 
	 * nothing.
	 */
	
        
        
	
}
